/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpi.cpo.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * ChargingProfilePeriod
 */
@JsonPropertyOrder({
        ChargingProfilePeriod.JSON_PROPERTY_START_PERIOD,
        ChargingProfilePeriod.JSON_PROPERTY_LIMIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-29T18:01:53.215553+03:00[Europe/Kiev]")
public class ChargingProfilePeriod {
  public static final String JSON_PROPERTY_START_PERIOD = "start_period";
  private Integer startPeriod;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  private Float limit;

  public ChargingProfilePeriod() {
  }

  public ChargingProfilePeriod startPeriod(Integer startPeriod) {
    
    this.startPeriod = startPeriod;
    return this;
  }

   /**
   * Get startPeriod
   * @return startPeriod
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_START_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getStartPeriod() {
    return startPeriod;
  }


  @JsonProperty(JSON_PROPERTY_START_PERIOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStartPeriod(Integer startPeriod) {
    this.startPeriod = startPeriod;
  }


  public ChargingProfilePeriod limit(Float limit) {
    
    this.limit = limit;
    return this;
  }

   /**
   * Get limit
   * @return limit
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getLimit() {
    return limit;
  }


  @JsonProperty(JSON_PROPERTY_LIMIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLimit(Float limit) {
    this.limit = limit;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ChargingProfilePeriod chargingProfilePeriod = (ChargingProfilePeriod) o;
    return Objects.equals(this.startPeriod, chargingProfilePeriod.startPeriod) &&
        Objects.equals(this.limit, chargingProfilePeriod.limit);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startPeriod, limit);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ChargingProfilePeriod {\n");
    sb.append("    startPeriod: ").append(toIndentedString(startPeriod)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

