/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpi.cpo.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EnergyMix
 */
@JsonPropertyOrder({
        EnergyMix.JSON_PROPERTY_IS_GREEN_ENERGY,
        EnergyMix.JSON_PROPERTY_ENERGY_SOURCES,
        EnergyMix.JSON_PROPERTY_ENVIRON_IMPACT,
        EnergyMix.JSON_PROPERTY_SUPPLIER_NAME,
        EnergyMix.JSON_PROPERTY_ENERGY_PRODUCT_NAME
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-29T16:33:36.372088+03:00[Europe/Kiev]")
public class EnergyMix {
  public static final String JSON_PROPERTY_IS_GREEN_ENERGY = "is_green_energy";
  private Boolean isGreenEnergy;

  public static final String JSON_PROPERTY_ENERGY_SOURCES = "energy_sources";
  private List<EnergySource> energySources;

  public static final String JSON_PROPERTY_ENVIRON_IMPACT = "environ_impact";
  private List<EnvironmentalImpact> environImpact;

  public static final String JSON_PROPERTY_SUPPLIER_NAME = "supplier_name";
  private String supplierName;

  public static final String JSON_PROPERTY_ENERGY_PRODUCT_NAME = "energy_product_name";
  private String energyProductName;

  public EnergyMix() {
  }

  public EnergyMix isGreenEnergy(Boolean isGreenEnergy) {
    
    this.isGreenEnergy = isGreenEnergy;
    return this;
  }

   /**
   * Get isGreenEnergy
   * @return isGreenEnergy
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_GREEN_ENERGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsGreenEnergy() {
    return isGreenEnergy;
  }


  @JsonProperty(JSON_PROPERTY_IS_GREEN_ENERGY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsGreenEnergy(Boolean isGreenEnergy) {
    this.isGreenEnergy = isGreenEnergy;
  }


  public EnergyMix energySources(List<EnergySource> energySources) {
    
    this.energySources = energySources;
    return this;
  }

  public EnergyMix addEnergySourcesItem(EnergySource energySourcesItem) {
    if (this.energySources == null) {
      this.energySources = new ArrayList<>();
    }
    this.energySources.add(energySourcesItem);
    return this;
  }

   /**
   * Get energySources
   * @return energySources
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENERGY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EnergySource> getEnergySources() {
    return energySources;
  }


  @JsonProperty(JSON_PROPERTY_ENERGY_SOURCES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnergySources(List<EnergySource> energySources) {
    this.energySources = energySources;
  }


  public EnergyMix environImpact(List<EnvironmentalImpact> environImpact) {
    
    this.environImpact = environImpact;
    return this;
  }

  public EnergyMix addEnvironImpactItem(EnvironmentalImpact environImpactItem) {
    if (this.environImpact == null) {
      this.environImpact = new ArrayList<>();
    }
    this.environImpact.add(environImpactItem);
    return this;
  }

   /**
   * Get environImpact
   * @return environImpact
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENVIRON_IMPACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EnvironmentalImpact> getEnvironImpact() {
    return environImpact;
  }


  @JsonProperty(JSON_PROPERTY_ENVIRON_IMPACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnvironImpact(List<EnvironmentalImpact> environImpact) {
    this.environImpact = environImpact;
  }


  public EnergyMix supplierName(String supplierName) {
    
    this.supplierName = supplierName;
    return this;
  }

   /**
   * Get supplierName
   * @return supplierName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUPPLIER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSupplierName() {
    return supplierName;
  }


  @JsonProperty(JSON_PROPERTY_SUPPLIER_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSupplierName(String supplierName) {
    this.supplierName = supplierName;
  }


  public EnergyMix energyProductName(String energyProductName) {
    
    this.energyProductName = energyProductName;
    return this;
  }

   /**
   * Get energyProductName
   * @return energyProductName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENERGY_PRODUCT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEnergyProductName() {
    return energyProductName;
  }


  @JsonProperty(JSON_PROPERTY_ENERGY_PRODUCT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnergyProductName(String energyProductName) {
    this.energyProductName = energyProductName;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnergyMix energyMix = (EnergyMix) o;
    return Objects.equals(this.isGreenEnergy, energyMix.isGreenEnergy) &&
        Objects.equals(this.energySources, energyMix.energySources) &&
        Objects.equals(this.environImpact, energyMix.environImpact) &&
        Objects.equals(this.supplierName, energyMix.supplierName) &&
        Objects.equals(this.energyProductName, energyMix.energyProductName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isGreenEnergy, energySources, environImpact, supplierName, energyProductName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnergyMix {\n");
    sb.append("    isGreenEnergy: ").append(toIndentedString(isGreenEnergy)).append("\n");
    sb.append("    energySources: ").append(toIndentedString(energySources)).append("\n");
    sb.append("    environImpact: ").append(toIndentedString(environImpact)).append("\n");
    sb.append("    supplierName: ").append(toIndentedString(supplierName)).append("\n");
    sb.append("    energyProductName: ").append(toIndentedString(energyProductName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

