/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpi.cpo.client.model;

import com.fasterxml.jackson.annotation.*;

import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * LocationDTO
 */
@JsonPropertyOrder({
  LocationDTO.JSON_PROPERTY_ID,
  LocationDTO.JSON_PROPERTY_PUBLISH,
  LocationDTO.JSON_PROPERTY_NAME,
  LocationDTO.JSON_PROPERTY_ADDRESS,
  LocationDTO.JSON_PROPERTY_CITY,
  LocationDTO.JSON_PROPERTY_STATE,
  LocationDTO.JSON_PROPERTY_COUNTRY,
  LocationDTO.JSON_PROPERTY_COORDINATES,
  LocationDTO.JSON_PROPERTY_EVSES,
  LocationDTO.JSON_PROPERTY_DIRECTIONS,
  LocationDTO.JSON_PROPERTY_OPERATOR,
  LocationDTO.JSON_PROPERTY_SUB_OPERATOR,
  LocationDTO.JSON_PROPERTY_OWNER,
  LocationDTO.JSON_PROPERTY_FACILITIES,
  LocationDTO.JSON_PROPERTY_IMAGES,
  LocationDTO.JSON_PROPERTY_COUNTRY_CODE,
  LocationDTO.JSON_PROPERTY_PARTY_ID,
  LocationDTO.JSON_PROPERTY_PUBLISH_ALLOWED_TO,
  LocationDTO.JSON_PROPERTY_POSTAL_CODE,
  LocationDTO.JSON_PROPERTY_RELATED_LOCATIONS,
  LocationDTO.JSON_PROPERTY_PARKING_TYPE,
  LocationDTO.JSON_PROPERTY_TIME_ZONE,
  LocationDTO.JSON_PROPERTY_OPENING_TIMES,
  LocationDTO.JSON_PROPERTY_CHARGING_WHEN_CLOSED,
  LocationDTO.JSON_PROPERTY_ENERGY_MIX,
  LocationDTO.JSON_PROPERTY_LAST_UPDATED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-18T12:07:41.590741+03:00[Europe/Kiev]")
public class LocationDTO {
  public static final String JSON_PROPERTY_ID = "id";
  private String id;

  public static final String JSON_PROPERTY_PUBLISH = "publish";
  private Boolean publish;

  public static final String JSON_PROPERTY_NAME = "name";
  private String name;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_CITY = "city";
  private String city;

  public static final String JSON_PROPERTY_STATE = "state";
  private String state;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  private String country;

  public static final String JSON_PROPERTY_COORDINATES = "coordinates";
  private GeoLocation coordinates;

  public static final String JSON_PROPERTY_EVSES = "evses";
  private List<EVSE> evses;

  public static final String JSON_PROPERTY_DIRECTIONS = "directions";
  private List<DisplayText> directions;

  public static final String JSON_PROPERTY_OPERATOR = "operator";
  private BusinessDetails operator;

  public static final String JSON_PROPERTY_SUB_OPERATOR = "subOperator";
  private BusinessDetails subOperator;

  public static final String JSON_PROPERTY_OWNER = "owner";
  private BusinessDetails owner;

  /**
   * Gets or Sets facilities
   */
  public enum FacilitiesEnum {
    HOTEL("HOTEL"),
    
    RESTAURANT("RESTAURANT"),
    
    CAFE("CAFE"),
    
    MALL("MALL"),
    
    SUPERMARKET("SUPERMARKET"),
    
    SPORT("SPORT"),
    
    RECREATION_AREA("RECREATION_AREA"),
    
    NATURE("NATURE"),
    
    MUSEUM("MUSEUM"),
    
    BIKE_SHARING("BIKE_SHARING"),
    
    BUS_STOP("BUS_STOP"),
    
    TAXI_STAND("TAXI_STAND"),
    
    TRAM_STOP("TRAM_STOP"),
    
    METRO_STATION("METRO_STATION"),
    
    TRAIN_STATION("TRAIN_STATION"),
    
    AIRPORT("AIRPORT"),
    
    PARKING_LOT("PARKING_LOT"),
    
    CARPOOL_PARKING("CARPOOL_PARKING"),
    
    FUEL_STATION("FUEL_STATION"),
    
    WIFI("WIFI");

    private String value;

    FacilitiesEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FacilitiesEnum fromValue(String value) {
      for (FacilitiesEnum b : FacilitiesEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FACILITIES = "facilities";
  private List<FacilitiesEnum> facilities;

  public static final String JSON_PROPERTY_IMAGES = "images";
  private List<Image> images;

  public static final String JSON_PROPERTY_COUNTRY_CODE = "country_code";
  private String countryCode;

  public static final String JSON_PROPERTY_PARTY_ID = "party_id";
  private String partyId;

  public static final String JSON_PROPERTY_PUBLISH_ALLOWED_TO = "publish_allowed_to";
  private List<PublishTokenType> publishAllowedTo;

  public static final String JSON_PROPERTY_POSTAL_CODE = "postal_code";
  private String postalCode;

  public static final String JSON_PROPERTY_RELATED_LOCATIONS = "related_locations";
  private List<AdditionalGeoLocation> relatedLocations;

  /**
   * Gets or Sets parkingType
   */
  public enum ParkingTypeEnum {
    ALONG_MOTORWAY("ALONG_MOTORWAY"),
    
    PARKING_GARAGE("PARKING_GARAGE"),
    
    PARKING_LOT("PARKING_LOT"),
    
    ON_DRIVEWAY("ON_DRIVEWAY"),
    
    ON_STREET("ON_STREET"),
    
    UNDERGROUND_GARAGE("UNDERGROUND_GARAGE");

    private String value;

    ParkingTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ParkingTypeEnum fromValue(String value) {
      for (ParkingTypeEnum b : ParkingTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_PARKING_TYPE = "parking_type";
  private ParkingTypeEnum parkingType;

  public static final String JSON_PROPERTY_TIME_ZONE = "time_zone";
  private String timeZone;

  public static final String JSON_PROPERTY_OPENING_TIMES = "opening_times";
  private Hours openingTimes;

  public static final String JSON_PROPERTY_CHARGING_WHEN_CLOSED = "charging_when_closed";
  private Boolean chargingWhenClosed;

  public static final String JSON_PROPERTY_ENERGY_MIX = "energy_mix";
  private EnergyMix energyMix;

  public static final String JSON_PROPERTY_LAST_UPDATED = "last_updated";
  private OffsetDateTime lastUpdated;

  public LocationDTO() {
  }

  public LocationDTO id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(String id) {
    this.id = id;
  }


  public LocationDTO publish(Boolean publish) {
    
    this.publish = publish;
    return this;
  }

   /**
   * Get publish
   * @return publish
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PUBLISH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Boolean getPublish() {
    return publish;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPublish(Boolean publish) {
    this.publish = publish;
  }


  public LocationDTO name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(String name) {
    this.name = name;
  }


  public LocationDTO address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAddress(String address) {
    this.address = address;
  }


  public LocationDTO city(String city) {
    
    this.city = city;
    return this;
  }

   /**
   * Get city
   * @return city
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCity() {
    return city;
  }


  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCity(String city) {
    this.city = city;
  }


  public LocationDTO state(String state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getState() {
    return state;
  }


  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(String state) {
    this.state = state;
  }


  public LocationDTO country(String country) {
    
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCountry() {
    return country;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCountry(String country) {
    this.country = country;
  }


  public LocationDTO coordinates(GeoLocation coordinates) {
    
    this.coordinates = coordinates;
    return this;
  }

   /**
   * Get coordinates
   * @return coordinates
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COORDINATES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public GeoLocation getCoordinates() {
    return coordinates;
  }


  @JsonProperty(JSON_PROPERTY_COORDINATES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCoordinates(GeoLocation coordinates) {
    this.coordinates = coordinates;
  }


  public LocationDTO evses(List<EVSE> evses) {
    
    this.evses = evses;
    return this;
  }

  public LocationDTO addEvsesItem(EVSE evsesItem) {
    if (this.evses == null) {
      this.evses = new ArrayList<>();
    }
    this.evses.add(evsesItem);
    return this;
  }

   /**
   * Get evses
   * @return evses
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<EVSE> getEvses() {
    return evses;
  }


  @JsonProperty(JSON_PROPERTY_EVSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEvses(List<EVSE> evses) {
    this.evses = evses;
  }


  public LocationDTO directions(List<DisplayText> directions) {
    
    this.directions = directions;
    return this;
  }

  public LocationDTO addDirectionsItem(DisplayText directionsItem) {
    if (this.directions == null) {
      this.directions = new ArrayList<>();
    }
    this.directions.add(directionsItem);
    return this;
  }

   /**
   * Get directions
   * @return directions
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DIRECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<DisplayText> getDirections() {
    return directions;
  }


  @JsonProperty(JSON_PROPERTY_DIRECTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirections(List<DisplayText> directions) {
    this.directions = directions;
  }


  public LocationDTO operator(BusinessDetails operator) {
    
    this.operator = operator;
    return this;
  }

   /**
   * Get operator
   * @return operator
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BusinessDetails getOperator() {
    return operator;
  }


  @JsonProperty(JSON_PROPERTY_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOperator(BusinessDetails operator) {
    this.operator = operator;
  }


  public LocationDTO subOperator(BusinessDetails subOperator) {
    
    this.subOperator = subOperator;
    return this;
  }

   /**
   * Get subOperator
   * @return subOperator
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUB_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BusinessDetails getSubOperator() {
    return subOperator;
  }


  @JsonProperty(JSON_PROPERTY_SUB_OPERATOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSubOperator(BusinessDetails subOperator) {
    this.subOperator = subOperator;
  }


  public LocationDTO owner(BusinessDetails owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BusinessDetails getOwner() {
    return owner;
  }


  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOwner(BusinessDetails owner) {
    this.owner = owner;
  }


  public LocationDTO facilities(List<FacilitiesEnum> facilities) {
    
    this.facilities = facilities;
    return this;
  }

  public LocationDTO addFacilitiesItem(FacilitiesEnum facilitiesItem) {
    if (this.facilities == null) {
      this.facilities = new ArrayList<>();
    }
    this.facilities.add(facilitiesItem);
    return this;
  }

   /**
   * Get facilities
   * @return facilities
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FACILITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<FacilitiesEnum> getFacilities() {
    return facilities;
  }


  @JsonProperty(JSON_PROPERTY_FACILITIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFacilities(List<FacilitiesEnum> facilities) {
    this.facilities = facilities;
  }


  public LocationDTO images(List<Image> images) {
    
    this.images = images;
    return this;
  }

  public LocationDTO addImagesItem(Image imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * Get images
   * @return images
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<Image> getImages() {
    return images;
  }


  @JsonProperty(JSON_PROPERTY_IMAGES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setImages(List<Image> images) {
    this.images = images;
  }


  public LocationDTO countryCode(String countryCode) {
    
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Get countryCode
   * @return countryCode
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getCountryCode() {
    return countryCode;
  }


  @JsonProperty(JSON_PROPERTY_COUNTRY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }


  public LocationDTO partyId(String partyId) {
    
    this.partyId = partyId;
    return this;
  }

   /**
   * Get partyId
   * @return partyId
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getPartyId() {
    return partyId;
  }


  @JsonProperty(JSON_PROPERTY_PARTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPartyId(String partyId) {
    this.partyId = partyId;
  }


  public LocationDTO publishAllowedTo(List<PublishTokenType> publishAllowedTo) {
    
    this.publishAllowedTo = publishAllowedTo;
    return this;
  }

  public LocationDTO addPublishAllowedToItem(PublishTokenType publishAllowedToItem) {
    if (this.publishAllowedTo == null) {
      this.publishAllowedTo = new ArrayList<>();
    }
    this.publishAllowedTo.add(publishAllowedToItem);
    return this;
  }

   /**
   * Get publishAllowedTo
   * @return publishAllowedTo
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISH_ALLOWED_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PublishTokenType> getPublishAllowedTo() {
    return publishAllowedTo;
  }


  @JsonProperty(JSON_PROPERTY_PUBLISH_ALLOWED_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPublishAllowedTo(List<PublishTokenType> publishAllowedTo) {
    this.publishAllowedTo = publishAllowedTo;
  }


  public LocationDTO postalCode(String postalCode) {
    
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Get postalCode
   * @return postalCode
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPostalCode() {
    return postalCode;
  }


  @JsonProperty(JSON_PROPERTY_POSTAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  public LocationDTO relatedLocations(List<AdditionalGeoLocation> relatedLocations) {
    
    this.relatedLocations = relatedLocations;
    return this;
  }

  public LocationDTO addRelatedLocationsItem(AdditionalGeoLocation relatedLocationsItem) {
    if (this.relatedLocations == null) {
      this.relatedLocations = new ArrayList<>();
    }
    this.relatedLocations.add(relatedLocationsItem);
    return this;
  }

   /**
   * Get relatedLocations
   * @return relatedLocations
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RELATED_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<AdditionalGeoLocation> getRelatedLocations() {
    return relatedLocations;
  }


  @JsonProperty(JSON_PROPERTY_RELATED_LOCATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRelatedLocations(List<AdditionalGeoLocation> relatedLocations) {
    this.relatedLocations = relatedLocations;
  }


  public LocationDTO parkingType(ParkingTypeEnum parkingType) {
    
    this.parkingType = parkingType;
    return this;
  }

   /**
   * Get parkingType
   * @return parkingType
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PARKING_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public ParkingTypeEnum getParkingType() {
    return parkingType;
  }


  @JsonProperty(JSON_PROPERTY_PARKING_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParkingType(ParkingTypeEnum parkingType) {
    this.parkingType = parkingType;
  }


  public LocationDTO timeZone(String timeZone) {
    
    this.timeZone = timeZone;
    return this;
  }

   /**
   * Get timeZone
   * @return timeZone
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TIME_ZONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTimeZone() {
    return timeZone;
  }


  @JsonProperty(JSON_PROPERTY_TIME_ZONE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }


  public LocationDTO openingTimes(Hours openingTimes) {
    
    this.openingTimes = openingTimes;
    return this;
  }

   /**
   * Get openingTimes
   * @return openingTimes
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_OPENING_TIMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Hours getOpeningTimes() {
    return openingTimes;
  }


  @JsonProperty(JSON_PROPERTY_OPENING_TIMES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOpeningTimes(Hours openingTimes) {
    this.openingTimes = openingTimes;
  }


  public LocationDTO chargingWhenClosed(Boolean chargingWhenClosed) {
    
    this.chargingWhenClosed = chargingWhenClosed;
    return this;
  }

   /**
   * Get chargingWhenClosed
   * @return chargingWhenClosed
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHARGING_WHEN_CLOSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getChargingWhenClosed() {
    return chargingWhenClosed;
  }


  @JsonProperty(JSON_PROPERTY_CHARGING_WHEN_CLOSED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChargingWhenClosed(Boolean chargingWhenClosed) {
    this.chargingWhenClosed = chargingWhenClosed;
  }


  public LocationDTO energyMix(EnergyMix energyMix) {
    
    this.energyMix = energyMix;
    return this;
  }

   /**
   * Get energyMix
   * @return energyMix
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ENERGY_MIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public EnergyMix getEnergyMix() {
    return energyMix;
  }


  @JsonProperty(JSON_PROPERTY_ENERGY_MIX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEnergyMix(EnergyMix energyMix) {
    this.energyMix = energyMix;
  }


  public LocationDTO lastUpdated(OffsetDateTime lastUpdated) {
    
    this.lastUpdated = lastUpdated;
    return this;
  }

   /**
   * Get lastUpdated
   * @return lastUpdated
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getLastUpdated() {
    return lastUpdated;
  }


  @JsonProperty(JSON_PROPERTY_LAST_UPDATED)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLastUpdated(OffsetDateTime lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LocationDTO locationDTO = (LocationDTO) o;
    return Objects.equals(this.id, locationDTO.id) &&
        Objects.equals(this.publish, locationDTO.publish) &&
        Objects.equals(this.name, locationDTO.name) &&
        Objects.equals(this.address, locationDTO.address) &&
        Objects.equals(this.city, locationDTO.city) &&
        Objects.equals(this.state, locationDTO.state) &&
        Objects.equals(this.country, locationDTO.country) &&
        Objects.equals(this.coordinates, locationDTO.coordinates) &&
        Objects.equals(this.evses, locationDTO.evses) &&
        Objects.equals(this.directions, locationDTO.directions) &&
        Objects.equals(this.operator, locationDTO.operator) &&
        Objects.equals(this.subOperator, locationDTO.subOperator) &&
        Objects.equals(this.owner, locationDTO.owner) &&
        Objects.equals(this.facilities, locationDTO.facilities) &&
        Objects.equals(this.images, locationDTO.images) &&
        Objects.equals(this.countryCode, locationDTO.countryCode) &&
        Objects.equals(this.partyId, locationDTO.partyId) &&
        Objects.equals(this.publishAllowedTo, locationDTO.publishAllowedTo) &&
        Objects.equals(this.postalCode, locationDTO.postalCode) &&
        Objects.equals(this.relatedLocations, locationDTO.relatedLocations) &&
        Objects.equals(this.parkingType, locationDTO.parkingType) &&
        Objects.equals(this.timeZone, locationDTO.timeZone) &&
        Objects.equals(this.openingTimes, locationDTO.openingTimes) &&
        Objects.equals(this.chargingWhenClosed, locationDTO.chargingWhenClosed) &&
        Objects.equals(this.energyMix, locationDTO.energyMix) &&
        Objects.equals(this.lastUpdated, locationDTO.lastUpdated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, publish, name, address, city, state, country, coordinates, evses, directions, operator, subOperator, owner, facilities, images, countryCode, partyId, publishAllowedTo, postalCode, relatedLocations, parkingType, timeZone, openingTimes, chargingWhenClosed, energyMix, lastUpdated);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LocationDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    publish: ").append(toIndentedString(publish)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    coordinates: ").append(toIndentedString(coordinates)).append("\n");
    sb.append("    evses: ").append(toIndentedString(evses)).append("\n");
    sb.append("    directions: ").append(toIndentedString(directions)).append("\n");
    sb.append("    operator: ").append(toIndentedString(operator)).append("\n");
    sb.append("    subOperator: ").append(toIndentedString(subOperator)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    facilities: ").append(toIndentedString(facilities)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    partyId: ").append(toIndentedString(partyId)).append("\n");
    sb.append("    publishAllowedTo: ").append(toIndentedString(publishAllowedTo)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("    relatedLocations: ").append(toIndentedString(relatedLocations)).append("\n");
    sb.append("    parkingType: ").append(toIndentedString(parkingType)).append("\n");
    sb.append("    timeZone: ").append(toIndentedString(timeZone)).append("\n");
    sb.append("    openingTimes: ").append(toIndentedString(openingTimes)).append("\n");
    sb.append("    chargingWhenClosed: ").append(toIndentedString(chargingWhenClosed)).append("\n");
    sb.append("    energyMix: ").append(toIndentedString(energyMix)).append("\n");
    sb.append("    lastUpdated: ").append(toIndentedString(lastUpdated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

