/*
 * OCPI 2.2.1
 * This API exposes endpoints to manage OCPI entities.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: ocpi@extrawest.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.extrawest.ocpi.cpo.client.model;

import com.fasterxml.jackson.annotation.*;

import java.time.OffsetDateTime;
import java.util.Objects;

/**
 * StatusSchedule
 */
@JsonPropertyOrder({
  StatusSchedule.JSON_PROPERTY_PERIOD_BEGIN,
  StatusSchedule.JSON_PROPERTY_PERIOD_END,
  StatusSchedule.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-08-17T17:07:56.219565+03:00[Europe/Kiev]")
public class StatusSchedule {
  public static final String JSON_PROPERTY_PERIOD_BEGIN = "period_begin";
  private OffsetDateTime periodBegin;

  public static final String JSON_PROPERTY_PERIOD_END = "period_end";
  private OffsetDateTime periodEnd;

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    AVAILABLE("AVAILABLE"),
    
    BLOCKED("BLOCKED"),
    
    CHARGING("CHARGING"),
    
    INOPERATIVE("INOPERATIVE"),
    
    OUTOFORDER("OUTOFORDER"),
    
    PLANNED("PLANNED"),
    
    REMOVED("REMOVED"),
    
    RESERVED("RESERVED"),
    
    UNKNOWN("UNKNOWN");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  private StatusEnum status;

  public StatusSchedule() {
  }

  public StatusSchedule periodBegin(OffsetDateTime periodBegin) {
    
    this.periodBegin = periodBegin;
    return this;
  }

   /**
   * Get periodBegin
   * @return periodBegin
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERIOD_BEGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPeriodBegin() {
    return periodBegin;
  }


  @JsonProperty(JSON_PROPERTY_PERIOD_BEGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriodBegin(OffsetDateTime periodBegin) {
    this.periodBegin = periodBegin;
  }


  public StatusSchedule periodEnd(OffsetDateTime periodEnd) {
    
    this.periodEnd = periodEnd;
    return this;
  }

   /**
   * Get periodEnd
   * @return periodEnd
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERIOD_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getPeriodEnd() {
    return periodEnd;
  }


  @JsonProperty(JSON_PROPERTY_PERIOD_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPeriodEnd(OffsetDateTime periodEnd) {
    this.periodEnd = periodEnd;
  }


  public StatusSchedule status(StatusEnum status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StatusSchedule statusSchedule = (StatusSchedule) o;
    return Objects.equals(this.periodBegin, statusSchedule.periodBegin) &&
        Objects.equals(this.periodEnd, statusSchedule.periodEnd) &&
        Objects.equals(this.status, statusSchedule.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(periodBegin, periodEnd, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusSchedule {\n");
    sb.append("    periodBegin: ").append(toIndentedString(periodBegin)).append("\n");
    sb.append("    periodEnd: ").append(toIndentedString(periodEnd)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

